agent_id: 104
agent_manager_addr: "http://localhost:8080"
memspace_manager_addr: "http://localhost:7000"
chat_server_addr: "http://localhost:20001"
vector_server_addr: "http://localhost:5000"
role: "JobAgent"
image: "nucleus-agent:v1"
path: "/usr/bin/agent"
is_job: true
http_addr: "localhost:9004"