node_id: 2
monitor_url: "http://localhost:9101"
memspace_manager_url: "http://localhost:9200"
memspace_urls:
  1001: "http://localhost:8081"
#  1002: "http://localhost:8082"
#  1003: "http://localhost:8083"